name: linting, building, testing
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        node-version: [ 17.x ]
      # The runners that the job will run on
      runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install node_modules
        run: npm install
      - name: build production
        run: npm run build
      - name: linting ts
        run: npm run lint
      - name: linting scss
        run: npm run lint:style
      - name: unit testing
        run: npm run test:unit