name: linting, building, testing
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Linting TypeScript
        run: npm run lint
      - name: Linting TypeScript
        run: npm run lint:fix

#      -name: Linting SCSS
#       run: npm run lint:style

      - name: Unit Testing
        run: npm run test:unit

      - name: Build production
        run: npm run build:prod